### ISSUE TITLE
Alternate license?

### ISSUE THREAD

**Issue by lazerwalker** [ezefranca/WatchShaker#3]
First of all, thanks so much for this. It looks absolutely lovely!

However: while I'm interested in using it for a project, I'm concerned about its use of the GPL. Specifically, it's widely believed that the terms of the GPL are generally [incompatible with the iOS App Store terms of service](http://www.zdnet.com/article/no-gpl-apps-for-apples-app-store/) (there are some exceptions and caveats to that, but they don't really apply here).

Is there any chance you'd be willing to relicense this library under a more permissive license, such as the MIT or BSD license? I fully understand if not, and if you don't feel comfortable licensing this under a non-copyleft license, but as it stands I don't think there is any way for anyone to use your library with their Apple Watch app and also release it on the App Store, even if their app is also GPL.

(If this isn't something you're too familiar with, happy to explain more or answer questions, with the caveat that I am not a lawyer).

**Comment by ezefranca** [comment]
Hi @lazerwalker, thanks of your comment!

In the past, [one of my projects ](https://github.com/ezefranca/FSK-Arduino-iOS/issues/4)was used in MIT Media Lab (I saw your profile 😅).

I has been using MIT License, I think the GPL here is a mistake when I created the repository on GitHub. 

I changed to MIT again! Thank you very much 🎉
