### ISSUE TITLE
Missing master/img/bwshaker.jpg

### ISSUE THREAD

**Issue by ghv** [ezefranca/WatchShaker#8]
Can you upload the image to the repo?

**Comment by ghv** [comment]
Also, the Swift version image is broken:

`[![Swift Version][swift-image]][swift-url]`

Perhaps that should be:

`[![Swift Version 3.0](swift-image)](swift-url)`

[![Swift Version 3.0](https://img.shields.io/badge/Swift-3.0-orange.svg)](https://swift.org/)

**Comment by ezefranca** [comment]
I changed my site domain and losted. Thanks again! Fixed
